
export const FETCH_RANDOMNUMBERS = 'FETCH_RANDOMNUMBERS';
export const UPDATE_USER_INPUT = 'UPDATE_USER_INPUT';
export const FORMAT_NUMBERS_CHART_DATA = 'FORMAT_NUMBERS_CHART_DATA';
export const RELOAD_CHART = 'RELOAD_CHART';
